### PR TITLE
Add businesshours 

### PR DESCRIPTION
**Pull request by csoare7**
- Add methods to calculate businesstime_hours
- Add relevant tests

Related to https://github.com/seatgeek/businesstime/issues/20

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you add a test for the times being compared in reverse?

**Comment by csoare7** [comment]
Hey sure, thanks for the comment

**Comment by josegonzalez** [comment]
I'll need to see if I can get access to make a release - should be simple, but its probably associated to the CTO's pypi account so... ;)

**Comment by naes17** [comment]
First, thanks for this library! I replaced a bunch of obtuse code with it.

Second, why was the decision made to have the business_hours method return total seconds?
I needed it to return a datetime.timedelta just like the businesstimedelta method. I figure that makes more sense and it's also much easier to convert the output to total seconds.

[businesstime_hours.txt](https://github.com/seatgeek/businesstime/files/1516104/businesstime_hours.txt)

**Comment by josegonzalez** [comment]
@naes17 given that we havent made a release yet, if you want to change that, I'd gladly accept the change.

**Comment by csoare7** [comment]
@naes17 right you are! looking forward to your change 👍

**Pull request merged**
