### PR TITLE
Fix #14 -- pip not installing full package

### LINKED ISSUE #14: setup.py/pip does not install holidays
pip install businesstime and python setup.py install does not install the holidays submodule.

### PR DESCRIPTION
**Pull request by tarkatronic**
I also removed distutils, as this has long been deprecated, and I'm not actually certain if there is an equivalent to `find_packages` in distutils.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Fancy. Thanks!

**Comment by josegonzalez** [comment]
Note: I unfortunately don't have release rights for this project on pypi and the dev who does is on vacation at the moment. I'll be sure to pm him when he's pack so we can handle that :)

**Comment by erwaller** [comment]
Thanks @tarkatronic and @josegonzalez! v0.2.1 is up on pypi.

The one time I forget to install and try the package..

**Comment by josegonzalez** [comment]
@erwaller can you give me access to the pypi package? My nick is `savant` on pypi.

**Comment by erwaller** [comment]
@josegonzalez done

**Comment by josegonzalez** [comment]
:+1:

**Pull request merged**
